name: Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .env file from secret
        run: printf "%s\n" "${{ secrets.env }}" > .env

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Use the Docker Hub PAT stored as a secret

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .  # Point to the 'server' directory where your Dockerfile is located
          push: true
          tags: ${{ secrets.DOCKERHUB_TAGS }}
          
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          sudo docker system prune -f
          sudo docker pull ${{ secrets.DOCKERHUB_TAGS }}
          sudo docker rm -f $(sudo docker ps -a -q)
          sudo docker run -d -p 80:3000 ${{ secrets.DOCKERHUB_TAGS }}